export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_REQUEST_SUCCESS = 'GET_ORDERS_REQUEST_SUCCESS'
export const GET_ORDERS_REQUEST_FAIL = 'GET_ORDERS_REQUEST_FAIL'

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST'
export const GET_ORDER_BY_ID_REQUEST_SUCCESS = 'GET_ORDER_BY_ID_REQUEST_SUCCESS'
export const GET_ORDER_BY_ID_REQUEST_FAIL = 'GET_ORDER_BY_ID_REQUEST_FAIL'

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_REQUEST_SUCCESS = 'CREATE_ORDER_REQUEST_SUCCESS'
export const CREATE_ORDER_REQUEST_FAIL = 'CREATE_ORDER_REQUEST_FAIL'