export const RESERVE_REQUEST = 'RESERVE_REQUEST'
export const RESERVE_REQUEST_SUCCESS = 'RESERVE_REQUEST_SUCCESS'
export const RESERVE_REQUEST_FAIL = 'RESERVE_REQUEST_FAIL'

export const RELEASE_REQUEST = 'RELEASE_REQUEST'
export const RELEASE_REQUEST_SUCCESS = 'RELEASE_REQUEST_SUCCESS'
export const RELEASE_REQUEST_FAIL = 'RELEASE_REQUEST_FAIL'

export const REFUND_REQUEST = 'REFUND_REQUEST'
export const REFUND_REQUEST_SUCCESS = 'REFUND_REQUEST_SUCCESS'
export const REFUND_REQUEST_FAIL = 'REFUND_REQUEST_FAIL'

export const CAPTURE_REQUEST = 'CAPTURE_REQUEST'
export const CAPTURE_REQUEST_SUCCESS = 'CAPTURE_REQUEST_SUCCESS'
export const CAPTURE_REQUEST_FAIL = 'CAPTURE_REQUEST_FAIL'

export const FALLBACK = 'FALLBACK'